server:
  port: 8005
  servlet:
    context-path: /test
spring:
  devtools:
    remote:
      restart:
        enabled: false
  datasource:

    url: jdbc:mysql://127.0.0.1:3306/db_1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    data-username: root
    data-password: root
    tomcat:
           max-idle : 10
           max-active: 50
           max-wait : 10000
           initial-size : 5
           default-transaction-isolation : 2
mybatis :
    mapper-locations : classpath:mapper/*.xml
    type-aliases-package : com.mystore.entity


 
